#!/bin/env python3

import sys
import time
from threading import Thread

import task.knob
import task.trigger
import task.action
import config
import command




def main():

  # TODO: Load and sanity check format of configuration
  app_config = config.default_config()

  try:
    app_config = config.validate_config(app_config)
  except Exception as e:
    sys.exit(e.code)

  command.init()

  knob_thread = Thread(target=task.knob.main, args=(app_config,))
  trigger_thread = Thread(target=task.trigger.main, args=(app_config,))
  action_thread = Thread(target=task.action.main, args=(app_config,))


  knob_thread.start()
  trigger_thread.start()
  action_thread.start()

  try:
    time.sleep(10)
  except KeyboardInterrupt:
    pass


  command.stop_knob()
  command.stop_trigger()
  command.stop_action()

  knob_thread.join()
  trigger_thread.join()
  action_thread.join()


if __name__ == "__main__":
  main()
